export const products = [
  {
    id: 1,
    name: "Small Ecru Ceramic Compote",
    price: 49,
    image: "/products/mercer-grey-bowl.svg",
    desc: "Lorem ipsum dolor sit amet conse bolli tetur adipiscing elit.",
    bestSeller: true,
    new: false,
  },
  {
    id: 2,
    name: "Porcelain Dinner Plate",
    price: 49,
    image: "/products/Porcelain-Dinner-Plate.svg",
    desc: "Lorem ipsum dolor sit amet conse bolli tetur.",
    bestSeller: true,
    new: false,
  },
  {
    id: 3,
    name: "Warrick White Vase 20",
    price: 68,
    image: "/products/WarrickVase20inWhiteAVSSS22.svg",
    desc: "Lorem ipsum dolor sit amet conse bolli tetur adipiscing elit tortor eu.",
    bestSeller: true,
    new: false,
  },
  {
    id: 4,
    name: "Marin White Dinner Plate",
    price: 49,
    image: "/products/marin-blue-salad-plate.svg",
    desc: "Lorem ipsum dolor sit amet conse.",
    bestSeller: true,
    new: false,
  },
  {
    id: 5,
    name: "Tall Cream Ceramic Vase",
    price: 79,
    image: "/products/alura-cream-tall-vase.svg",
    desc: "Lorem ipsum dolor sit amet conse bolli tetur adipiscing elit.",
    bestSeller: true,
    new: false,
  },
  {
    id: 6,
    name: "Luana Bowl",
    price: 49,
    image: "/products/mercer-low-bowl.svg",
    desc: "Lorem ipsum dolor sit amet conse bolli tetur adipiscing elit tortor eu.",
    bestSeller: true,
    new: false,
  },
  {
    id: 7,
    name: "Ophelia Matte Natural Vase",
    price: 149,
    image: "/products/valo-matte-white-vase.svg",
    desc: "Lorem ipsum dolor sit amet conse bolli tetur.",
    bestSeller: false,
    new: true,
  },
  {
    id: 8,
    name: "Luana Bowl",
    price: 49,
    image: "/products/mercer-black-rim-bowl.svg",
    desc: "Lorem ipsum dolor sit amet conse.",
    bestSeller: false,
    new: true,
  },
  {
    id: 9,
    name: "Porcelain Dinner Plate",
    price: 49,
    image: "/products/julo-blue-salad-plate.svg",
    desc: "Lorem ipsum dolor sit amet conse bolli tetur adipiscing elit tortor eu.",
    bestSeller: false,
    new: true,
  },
  {
    id: 10,
    name: "Warrick White Vase 14",
    price: 49,
    image: "/products/holden-vase.svg",
    desc: "Lorem ipsum dolor sit amet conse bolli tetur adipiscing elit tortor eu.",
    bestSeller: true,
    new: false,
  },
  {
    id: 11,
    name: "Rounded Dual Handled Vase",
    price: 68,
    image: "/products/OpheliaVase17inWhiteAVSSS22.svg",
    desc: "Lorem ipsum dolor sit amet conse bolli tetur adipiscing elit tortor eu.",
    bestSeller: true,
    new: false,
  },
  {
    id: 12,
    name: "Porcelain Dinner Plate",
    price: 49,
    image: "/products/c4335f5f330dbeec64ad59bf6a0b4fd4.svg",
    desc: "Lorem ipsum dolor sit amet conse bolli tetur adipiscing elit tortor eu.",
    bestSeller: false,
    new: true,
  },
];
